import 'dart:convert';
import 'dart:io';

/// One-shot helper: merges the customer-incidents translation keys into every
/// assets/l10n/<code>.json file (adding only missing keys, preserving existing
/// content and order). Run once, then run tool/generate_app_strings.dart.
///
///   dart run tool/add_incident_strings.dart
Future<void> main() async {
  const dir = 'assets/l10n';

  for (final entry in _translations.entries) {
    final code = entry.key;
    final additions = entry.value;
    final file = File('$dir/$code.json');
    if (!file.existsSync()) {
      stderr.writeln('Missing $dir/$code.json — skipped');
      continue;
    }

    final map = (json.decode(await file.readAsString()) as Map)
        .cast<String, dynamic>();

    var added = 0;
    additions.forEach((key, value) {
      if (!map.containsKey(key)) {
        map[key] = value;
        added++;
      }
    });

    const encoder = JsonEncoder.withIndent('  ');
    await file.writeAsString('${encoder.convert(map)}\n');
    stdout.writeln('[$code] +$added keys (total ${map.length})');
  }
  stdout.writeln('Done. Now run: dart run tool/generate_app_strings.dart');
}

/// langCode -> (key -> translation).
const Map<String, Map<String, String>> _translations = {
  'en': {
    'customerIncidents': 'Customer Incidents',
    'incidentsNone': 'No incidents',
    'incidentFilterAll': 'All',
    'incidentTypePaymentFailed': 'Payment failed',
    'incidentTypeDriverCancelled': 'Driver cancelled',
    'incidentTypePassengerCancelled': 'Passenger cancelled',
    'incidentTypeLowRating': 'Low rating',
    'incidentTypeRefunded': 'Refunded',
    'incidentTypeLateClaim': 'Late-driver claim',
    'incidentDetails': 'Incident details',
    'incidentRecordings': 'Recordings',
    'incidentLocations': 'Locations',
    'incidentChat': 'Chat',
    'incidentInternalNotes': 'Internal notes',
    'incidentCustomer': 'Customer',
    'incidentPhone': 'Phone',
    'incidentTrip': 'Trip',
    'incidentTripStatus': 'Trip status',
    'incidentStatusOpen': 'Open',
    'incidentStatusInReview': 'In review',
    'incidentStatusResolved': 'Resolved',
    'incidentStatusDismissed': 'Dismissed',
    'incidentActionResolve': 'Resolve',
    'incidentActionDismiss': 'Dismiss',
    'incidentContactCustomer': 'Contact customer',
    'incidentRefund': 'Refund',
    'incidentSuspend': 'Suspend',
    'incidentReactivate': 'Reactivate',
    'incidentResolveTitle': 'Resolve incident',
    'incidentResolutionNoteHint': 'Resolution note (optional)',
    'incidentDismissTitle': 'Dismiss incident',
    'incidentReasonOptionalHint': 'Reason (optional)',
    'incidentMessageTitleHint': 'Title',
    'incidentMessageBodyHint': 'Message',
    'incidentSend': 'Send',
    'incidentConfirm': 'Confirm',
    'incidentRefundTitle': 'Issue refund',
    'incidentRefundAmountHint': 'Amount (leave empty for full refund)',
    'incidentSuspendTitle': 'Suspend customer',
    'incidentViewPhoto': 'View photo',
    'incidentWorking': 'Working...',
  },
  'ar': {
    'customerIncidents': 'حوادث العملاء',
    'incidentsNone': 'لا توجد حوادث',
    'incidentFilterAll': 'الكل',
    'incidentTypePaymentFailed': 'فشل الدفع',
    'incidentTypeDriverCancelled': 'ألغى السائق',
    'incidentTypePassengerCancelled': 'ألغى الراكب',
    'incidentTypeLowRating': 'تقييم منخفض',
    'incidentTypeRefunded': 'تم الاسترداد',
    'incidentTypeLateClaim': 'مطالبة تأخر السائق',
    'incidentDetails': 'تفاصيل الحادثة',
    'incidentRecordings': 'التسجيلات',
    'incidentLocations': 'المواقع',
    'incidentChat': 'المحادثة',
    'incidentInternalNotes': 'ملاحظات داخلية',
    'incidentCustomer': 'العميل',
    'incidentPhone': 'الهاتف',
    'incidentTrip': 'الرحلة',
    'incidentTripStatus': 'حالة الرحلة',
    'incidentStatusOpen': 'مفتوحة',
    'incidentStatusInReview': 'قيد المراجعة',
    'incidentStatusResolved': 'تم الحل',
    'incidentStatusDismissed': 'مرفوضة',
    'incidentActionResolve': 'حل',
    'incidentActionDismiss': 'رفض',
    'incidentContactCustomer': 'التواصل مع العميل',
    'incidentRefund': 'استرداد',
    'incidentSuspend': 'إيقاف',
    'incidentReactivate': 'إعادة تفعيل',
    'incidentResolveTitle': 'حل الحادثة',
    'incidentResolutionNoteHint': 'ملاحظة الحل (اختياري)',
    'incidentDismissTitle': 'رفض الحادثة',
    'incidentReasonOptionalHint': 'السبب (اختياري)',
    'incidentMessageTitleHint': 'العنوان',
    'incidentMessageBodyHint': 'الرسالة',
    'incidentSend': 'إرسال',
    'incidentConfirm': 'تأكيد',
    'incidentRefundTitle': 'إصدار استرداد',
    'incidentRefundAmountHint': 'المبلغ (اتركه فارغًا للاسترداد الكامل)',
    'incidentSuspendTitle': 'إيقاف العميل',
    'incidentViewPhoto': 'عرض الصورة',
    'incidentWorking': 'جارٍ التنفيذ...',
  },
  'nl': {
    'customerIncidents': 'Klantincidenten',
    'incidentsNone': 'Geen incidenten',
    'incidentFilterAll': 'Alle',
    'incidentTypePaymentFailed': 'Betaling mislukt',
    'incidentTypeDriverCancelled': 'Chauffeur geannuleerd',
    'incidentTypePassengerCancelled': 'Passagier geannuleerd',
    'incidentTypeLowRating': 'Lage beoordeling',
    'incidentTypeRefunded': 'Terugbetaald',
    'incidentTypeLateClaim': 'Claim chauffeur te laat',
    'incidentDetails': 'Incidentdetails',
    'incidentRecordings': 'Opnames',
    'incidentLocations': 'Locaties',
    'incidentChat': 'Chat',
    'incidentInternalNotes': 'Interne notities',
    'incidentCustomer': 'Klant',
    'incidentPhone': 'Telefoon',
    'incidentTrip': 'Rit',
    'incidentTripStatus': 'Ritstatus',
    'incidentStatusOpen': 'Open',
    'incidentStatusInReview': 'In behandeling',
    'incidentStatusResolved': 'Opgelost',
    'incidentStatusDismissed': 'Afgewezen',
    'incidentActionResolve': 'Oplossen',
    'incidentActionDismiss': 'Afwijzen',
    'incidentContactCustomer': 'Klant contacteren',
    'incidentRefund': 'Terugbetaling',
    'incidentSuspend': 'Schorsen',
    'incidentReactivate': 'Heractiveren',
    'incidentResolveTitle': 'Incident oplossen',
    'incidentResolutionNoteHint': 'Oplossingsnotitie (optioneel)',
    'incidentDismissTitle': 'Incident afwijzen',
    'incidentReasonOptionalHint': 'Reden (optioneel)',
    'incidentMessageTitleHint': 'Titel',
    'incidentMessageBodyHint': 'Bericht',
    'incidentSend': 'Verzenden',
    'incidentConfirm': 'Bevestigen',
    'incidentRefundTitle': 'Terugbetaling uitgeven',
    'incidentRefundAmountHint': 'Bedrag (leeg laten voor volledige terugbetaling)',
    'incidentSuspendTitle': 'Klant schorsen',
    'incidentViewPhoto': 'Foto bekijken',
    'incidentWorking': 'Bezig...',
  },
  'de': {
    'customerIncidents': 'Kundenvorfälle',
    'incidentsNone': 'Keine Vorfälle',
    'incidentFilterAll': 'Alle',
    'incidentTypePaymentFailed': 'Zahlung fehlgeschlagen',
    'incidentTypeDriverCancelled': 'Fahrer storniert',
    'incidentTypePassengerCancelled': 'Fahrgast storniert',
    'incidentTypeLowRating': 'Schlechte Bewertung',
    'incidentTypeRefunded': 'Erstattet',
    'incidentTypeLateClaim': 'Reklamation: Fahrer zu spät',
    'incidentDetails': 'Vorfalldetails',
    'incidentRecordings': 'Aufnahmen',
    'incidentLocations': 'Standorte',
    'incidentChat': 'Chat',
    'incidentInternalNotes': 'Interne Notizen',
    'incidentCustomer': 'Kunde',
    'incidentPhone': 'Telefon',
    'incidentTrip': 'Fahrt',
    'incidentTripStatus': 'Fahrtstatus',
    'incidentStatusOpen': 'Offen',
    'incidentStatusInReview': 'In Prüfung',
    'incidentStatusResolved': 'Gelöst',
    'incidentStatusDismissed': 'Abgelehnt',
    'incidentActionResolve': 'Lösen',
    'incidentActionDismiss': 'Ablehnen',
    'incidentContactCustomer': 'Kunde kontaktieren',
    'incidentRefund': 'Erstattung',
    'incidentSuspend': 'Sperren',
    'incidentReactivate': 'Reaktivieren',
    'incidentResolveTitle': 'Vorfall lösen',
    'incidentResolutionNoteHint': 'Lösungsnotiz (optional)',
    'incidentDismissTitle': 'Vorfall ablehnen',
    'incidentReasonOptionalHint': 'Grund (optional)',
    'incidentMessageTitleHint': 'Titel',
    'incidentMessageBodyHint': 'Nachricht',
    'incidentSend': 'Senden',
    'incidentConfirm': 'Bestätigen',
    'incidentRefundTitle': 'Erstattung veranlassen',
    'incidentRefundAmountHint': 'Betrag (leer lassen für volle Erstattung)',
    'incidentSuspendTitle': 'Kunde sperren',
    'incidentViewPhoto': 'Foto ansehen',
    'incidentWorking': 'Wird ausgeführt...',
  },
  'pl': {
    'customerIncidents': 'Zgłoszenia klientów',
    'incidentsNone': 'Brak zgłoszeń',
    'incidentFilterAll': 'Wszystkie',
    'incidentTypePaymentFailed': 'Płatność nieudana',
    'incidentTypeDriverCancelled': 'Kierowca anulował',
    'incidentTypePassengerCancelled': 'Pasażer anulował',
    'incidentTypeLowRating': 'Niska ocena',
    'incidentTypeRefunded': 'Zwrócono',
    'incidentTypeLateClaim': 'Roszczenie: kierowca spóźniony',
    'incidentDetails': 'Szczegóły zgłoszenia',
    'incidentRecordings': 'Nagrania',
    'incidentLocations': 'Lokalizacje',
    'incidentChat': 'Czat',
    'incidentInternalNotes': 'Notatki wewnętrzne',
    'incidentCustomer': 'Klient',
    'incidentPhone': 'Telefon',
    'incidentTrip': 'Przejazd',
    'incidentTripStatus': 'Status przejazdu',
    'incidentStatusOpen': 'Otwarte',
    'incidentStatusInReview': 'W trakcie przeglądu',
    'incidentStatusResolved': 'Rozwiązane',
    'incidentStatusDismissed': 'Odrzucone',
    'incidentActionResolve': 'Rozwiąż',
    'incidentActionDismiss': 'Odrzuć',
    'incidentContactCustomer': 'Skontaktuj się z klientem',
    'incidentRefund': 'Zwrot',
    'incidentSuspend': 'Zawieś',
    'incidentReactivate': 'Przywróć',
    'incidentResolveTitle': 'Rozwiąż zgłoszenie',
    'incidentResolutionNoteHint': 'Notatka rozwiązania (opcjonalnie)',
    'incidentDismissTitle': 'Odrzuć zgłoszenie',
    'incidentReasonOptionalHint': 'Powód (opcjonalnie)',
    'incidentMessageTitleHint': 'Tytuł',
    'incidentMessageBodyHint': 'Wiadomość',
    'incidentSend': 'Wyślij',
    'incidentConfirm': 'Potwierdź',
    'incidentRefundTitle': 'Wykonaj zwrot',
    'incidentRefundAmountHint': 'Kwota (puste = pełny zwrot)',
    'incidentSuspendTitle': 'Zawieś klienta',
    'incidentViewPhoto': 'Zobacz zdjęcie',
    'incidentWorking': 'Przetwarzanie...',
  },
  'uk': {
    'customerIncidents': 'Інциденти клієнтів',
    'incidentsNone': 'Немає інцидентів',
    'incidentFilterAll': 'Усі',
    'incidentTypePaymentFailed': 'Помилка оплати',
    'incidentTypeDriverCancelled': 'Водій скасував',
    'incidentTypePassengerCancelled': 'Пасажир скасував',
    'incidentTypeLowRating': 'Низька оцінка',
    'incidentTypeRefunded': 'Повернено',
    'incidentTypeLateClaim': 'Скарга: водій запізнився',
    'incidentDetails': 'Деталі інциденту',
    'incidentRecordings': 'Записи',
    'incidentLocations': 'Локації',
    'incidentChat': 'Чат',
    'incidentInternalNotes': 'Внутрішні нотатки',
    'incidentCustomer': 'Клієнт',
    'incidentPhone': 'Телефон',
    'incidentTrip': 'Поїздка',
    'incidentTripStatus': 'Статус поїздки',
    'incidentStatusOpen': 'Відкрито',
    'incidentStatusInReview': 'На розгляді',
    'incidentStatusResolved': 'Вирішено',
    'incidentStatusDismissed': 'Відхилено',
    'incidentActionResolve': 'Вирішити',
    'incidentActionDismiss': 'Відхилити',
    'incidentContactCustomer': 'Звʼязатися з клієнтом',
    'incidentRefund': 'Повернення',
    'incidentSuspend': 'Призупинити',
    'incidentReactivate': 'Відновити',
    'incidentResolveTitle': 'Вирішити інцидент',
    'incidentResolutionNoteHint': 'Нотатка про вирішення (необовʼязково)',
    'incidentDismissTitle': 'Відхилити інцидент',
    'incidentReasonOptionalHint': 'Причина (необовʼязково)',
    'incidentMessageTitleHint': 'Заголовок',
    'incidentMessageBodyHint': 'Повідомлення',
    'incidentSend': 'Надіслати',
    'incidentConfirm': 'Підтвердити',
    'incidentRefundTitle': 'Оформити повернення',
    'incidentRefundAmountHint': 'Сума (порожнє — повне повернення)',
    'incidentSuspendTitle': 'Призупинити клієнта',
    'incidentViewPhoto': 'Переглянути фото',
    'incidentWorking': 'Виконується...',
  },
  'fr': {
    'customerIncidents': 'Incidents clients',
    'incidentsNone': 'Aucun incident',
    'incidentFilterAll': 'Tous',
    'incidentTypePaymentFailed': 'Échec du paiement',
    'incidentTypeDriverCancelled': 'Annulé par le chauffeur',
    'incidentTypePassengerCancelled': 'Annulé par le passager',
    'incidentTypeLowRating': 'Mauvaise note',
    'incidentTypeRefunded': 'Remboursé',
    'incidentTypeLateClaim': 'Réclamation chauffeur en retard',
    'incidentDetails': 'Détails de l\'incident',
    'incidentRecordings': 'Enregistrements',
    'incidentLocations': 'Emplacements',
    'incidentChat': 'Discussion',
    'incidentInternalNotes': 'Notes internes',
    'incidentCustomer': 'Client',
    'incidentPhone': 'Téléphone',
    'incidentTrip': 'Trajet',
    'incidentTripStatus': 'Statut du trajet',
    'incidentStatusOpen': 'Ouvert',
    'incidentStatusInReview': 'En cours d\'examen',
    'incidentStatusResolved': 'Résolu',
    'incidentStatusDismissed': 'Rejeté',
    'incidentActionResolve': 'Résoudre',
    'incidentActionDismiss': 'Rejeter',
    'incidentContactCustomer': 'Contacter le client',
    'incidentRefund': 'Remboursement',
    'incidentSuspend': 'Suspendre',
    'incidentReactivate': 'Réactiver',
    'incidentResolveTitle': 'Résoudre l\'incident',
    'incidentResolutionNoteHint': 'Note de résolution (facultatif)',
    'incidentDismissTitle': 'Rejeter l\'incident',
    'incidentReasonOptionalHint': 'Motif (facultatif)',
    'incidentMessageTitleHint': 'Titre',
    'incidentMessageBodyHint': 'Message',
    'incidentSend': 'Envoyer',
    'incidentConfirm': 'Confirmer',
    'incidentRefundTitle': 'Émettre un remboursement',
    'incidentRefundAmountHint': 'Montant (vide = remboursement total)',
    'incidentSuspendTitle': 'Suspendre le client',
    'incidentViewPhoto': 'Voir la photo',
    'incidentWorking': 'En cours...',
  },
  'es': {
    'customerIncidents': 'Incidencias de clientes',
    'incidentsNone': 'Sin incidencias',
    'incidentFilterAll': 'Todas',
    'incidentTypePaymentFailed': 'Pago fallido',
    'incidentTypeDriverCancelled': 'Cancelado por el conductor',
    'incidentTypePassengerCancelled': 'Cancelado por el pasajero',
    'incidentTypeLowRating': 'Calificación baja',
    'incidentTypeRefunded': 'Reembolsado',
    'incidentTypeLateClaim': 'Reclamación por conductor tardío',
    'incidentDetails': 'Detalles de la incidencia',
    'incidentRecordings': 'Grabaciones',
    'incidentLocations': 'Ubicaciones',
    'incidentChat': 'Chat',
    'incidentInternalNotes': 'Notas internas',
    'incidentCustomer': 'Cliente',
    'incidentPhone': 'Teléfono',
    'incidentTrip': 'Viaje',
    'incidentTripStatus': 'Estado del viaje',
    'incidentStatusOpen': 'Abierta',
    'incidentStatusInReview': 'En revisión',
    'incidentStatusResolved': 'Resuelta',
    'incidentStatusDismissed': 'Descartada',
    'incidentActionResolve': 'Resolver',
    'incidentActionDismiss': 'Descartar',
    'incidentContactCustomer': 'Contactar al cliente',
    'incidentRefund': 'Reembolso',
    'incidentSuspend': 'Suspender',
    'incidentReactivate': 'Reactivar',
    'incidentResolveTitle': 'Resolver incidencia',
    'incidentResolutionNoteHint': 'Nota de resolución (opcional)',
    'incidentDismissTitle': 'Descartar incidencia',
    'incidentReasonOptionalHint': 'Motivo (opcional)',
    'incidentMessageTitleHint': 'Título',
    'incidentMessageBodyHint': 'Mensaje',
    'incidentSend': 'Enviar',
    'incidentConfirm': 'Confirmar',
    'incidentRefundTitle': 'Emitir reembolso',
    'incidentRefundAmountHint': 'Importe (vacío = reembolso total)',
    'incidentSuspendTitle': 'Suspender cliente',
    'incidentViewPhoto': 'Ver foto',
    'incidentWorking': 'Procesando...',
  },
  'ro': {
    'customerIncidents': 'Incidente clienți',
    'incidentsNone': 'Niciun incident',
    'incidentFilterAll': 'Toate',
    'incidentTypePaymentFailed': 'Plată eșuată',
    'incidentTypeDriverCancelled': 'Anulat de șofer',
    'incidentTypePassengerCancelled': 'Anulat de pasager',
    'incidentTypeLowRating': 'Evaluare scăzută',
    'incidentTypeRefunded': 'Rambursat',
    'incidentTypeLateClaim': 'Reclamație șofer întârziat',
    'incidentDetails': 'Detalii incident',
    'incidentRecordings': 'Înregistrări',
    'incidentLocations': 'Locații',
    'incidentChat': 'Chat',
    'incidentInternalNotes': 'Note interne',
    'incidentCustomer': 'Client',
    'incidentPhone': 'Telefon',
    'incidentTrip': 'Cursă',
    'incidentTripStatus': 'Stare cursă',
    'incidentStatusOpen': 'Deschis',
    'incidentStatusInReview': 'În verificare',
    'incidentStatusResolved': 'Rezolvat',
    'incidentStatusDismissed': 'Respins',
    'incidentActionResolve': 'Rezolvă',
    'incidentActionDismiss': 'Respinge',
    'incidentContactCustomer': 'Contactează clientul',
    'incidentRefund': 'Rambursare',
    'incidentSuspend': 'Suspendă',
    'incidentReactivate': 'Reactivează',
    'incidentResolveTitle': 'Rezolvă incidentul',
    'incidentResolutionNoteHint': 'Notă de rezolvare (opțional)',
    'incidentDismissTitle': 'Respinge incidentul',
    'incidentReasonOptionalHint': 'Motiv (opțional)',
    'incidentMessageTitleHint': 'Titlu',
    'incidentMessageBodyHint': 'Mesaj',
    'incidentSend': 'Trimite',
    'incidentConfirm': 'Confirmă',
    'incidentRefundTitle': 'Emite rambursare',
    'incidentRefundAmountHint': 'Sumă (gol = rambursare totală)',
    'incidentSuspendTitle': 'Suspendă clientul',
    'incidentViewPhoto': 'Vezi foto',
    'incidentWorking': 'Se procesează...',
  },
};
