# Generic Flutter Proguard rules
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# Google Maps Keep Rules
-keep class com.google.android.gms.maps.** { *; }
-keep interface com.google.android.gms.maps.** { *; }

# ObjectBox Keep Rules
-keep class io.objectbox.** { *; }
-keep interface io.objectbox.** { *; }
-keep class * extends io.objectbox.relation.ToOne { *; }
-keep class * extends io.objectbox.relation.ToMany { *; }
-keep class * extends io.objectbox.BoxStore { *; }
-keep class * extends io.objectbox.Box { *; }

# Keep Entity classes (generated by ObjectBox)
-keep class **.MyObjectBox { *; }
-keep class **._ { *; }

# Prevent obfuscation of some essential classes
-dontwarn io.objectbox.**
-dontwarn com.google.android.gms.**
-dontwarn com.google.android.play.core.**

# Keep Play Core classes if present
-keep class com.google.android.play.core.** { *; }
-keep interface com.google.android.play.core.** { *; }
